-- 1- Database Exploration

-- Explore All Objects in the Database
SELECT
	*
FROM INFORMATION_SCHEMA.TABLES;


-- Explore All Columns in the Database
SELECT 
	*
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';


-- 2- Dimenstion Exploration

-- Explore All Countries our customers Come from
SELECT 
	DISTINCT country 
FROM gold.dim_customers;


-- Explore All Categories "the major Divisions"
SELECT 
	DISTINCT category,
	subcategory,
	product_name
FROM gold.dim_products
ORDER BY 1,2,3;
	

-- 3- Date Exploration

-- Find the Date of the First and Last order
SELECT 
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS order_range_years
FROM gold.fact_sales;


-- Find the youngest and oldest customers 
SELECT 
	MIN(birthdate) AS oldest_birthdate,
	DATEDIFF(YEAR, MIN(birthdate), GETDATE()) AS oldest_age,
	MAX(birthdate) AS youngest_birthdate,
	DATEDIFF(YEAR, MAX(birthdate), GETDATE()) AS youngest_age
FROM gold.dim_customers;


-- 4- Measure Exploration

-- Find the Total Sales
SELECT 
	SUM(sales_amount) AS total_sales
FROM gold.fact_sales;


-- Find How Many items are Sold
SELECT 
	SUM(quantity) AS total_quantity
FROM gold.fact_sales;


-- Find the Average Selling Price
SELECT 
	AVG(price) AS avg_price
FROM gold.fact_sales;


-- Find the Total Number of Orders
SELECT 
	COUNT(order_number) AS total_orders
FROM gold.fact_sales;

SELECT 
	COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales;


-- Find the Total Number of Products
SELECT 
	COUNT(product_name) AS total_products
FROM gold.dim_products;

SELECT 
	COUNT(DISTINCT product_name) AS total_products
FROM gold.dim_products;

-- Find the Total Number of Customers 
SELECT 
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers;


-- Find the Total Number of Customers that has placed order 
SELECT 
	COUNT(DISTINCT customer_key) AS total_customers
FROM gold.fact_sales;


-- Generate a Report that shows all key metrics of the bussiness
SELECT 
	'Total Sales' AS measure_name,
	SUM(sales_amount) AS measure_value
FROM gold.fact_sales

UNION ALL

SELECT 
	'Total Quantity' AS measure_name,
	SUM(quantity) AS measure_value
FROM gold.fact_sales

UNION ALL 

SELECT 
	'Average Price' AS measure_name,
	AVG(price) 
FROM gold.fact_sales

UNION ALL

SELECT 
	'Total Number of Orders'AS measure_name,
	COUNT(DISTINCT order_number) 
FROM gold.fact_sales

UNION ALL

SELECT 
	'Total Number of Products' AS measure_name,
	COUNT(DISTINCT product_name)
FROM gold.dim_products

UNION ALL

SELECT 
	'Total NUmber of Customers' As measure_name ,
	COUNT(DISTINCT customer_key)
FROM gold.fact_sales;



-- 5- Magnitude Analysis

-- Find Total Customers by countries
SELECT 
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- Find the Total customer by gender
SELECT 
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- Find total products by category 
SELECT 
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- What is the average cost in each category?
SELECT 
	category,
	AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;


-- What is the total revenue generated for each category ?
SELECT 
	p.category,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
	ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- What is the total revenue generated by each customer?
SELECT 
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
	ON c.customer_key= f.customer_key
GROUP BY c.customer_key,c.first_name,c.last_name
ORDER BY total_revenue DESC;


-- What is the distribution of items sold across countries?
SELECT 
	c.country,
	SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
	ON c.customer_key= f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;



-- 6- Ranking Analysis

-- Which 5 products generate the highest revenue?
SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
	ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;


-- What are the 5 worst-performing products in terms of sales? 
SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
	ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC;


-- Find the top 10 customers who have generated the highest revenue
SELECT top 10
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
	ON c.customer_key= f.customer_key
GROUP BY c.customer_key,c.first_name,c.last_name
ORDER BY total_revenue DESC;


-- Find the 3 customers with the fewest orders placed
SELECT top 3
	c.customer_key,
	c.first_name,
	c.last_name,
	COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
	ON c.customer_key= f.customer_key
GROUP BY c.customer_key,c.first_name,c.last_name
ORDER BY total_orders ASC;